name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
    env:
      package: stash_phash

    name: Build for ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version: ~1.18

      - name: Build
        run: go build -o $package-$GOOS
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: amd64

      - name: Set Base Filename
        run: 'echo "filename=${{ env.package }}-${{ matrix.os }}" >> $GITHUB_ENV'

      - name: Add exe for Windows
        if: ${{ matrix.os == 'windows' }}
        run: 'echo "filename=${{ env.filename }}.exe" >> $GITHUB_ENV'

      - name: Rename File
        if: ${{ matrix.os == 'windows' }}
        run: mv $package-${{ matrix.os }} ${{ env.filename }}

      - uses: vimtor/action-zip@v1
        with:
          files: ${{ env.filename }}
          dest: ${{ env.package }}-${{ matrix.os }}.zip

      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: ${{ env.package }}-${{ matrix.os }}
          retention-days: 90
          path: ${{ env.package }}-${{ matrix.os }}.zip

  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            **/*.zip
